[package]
name = "rsping"
version = "1.0.0"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
colored = "3.0.0"
winapi = { version = "0.3.9", features = ["wincon", "winnt"] }
